//Contains all the products

export const productsData = [
  {
    id: 1,
    name: "Product 1",
    price: 29.99,
    image: "../images/alex-azabache-y2ErhoE92KA-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 2,
    name: "Product 2",
    price: 39.99,
    image: "../images/cornelia-ng-2zHQhfEpisc-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "Product 3",
    price: 49.99,
    image: "../images/luisana-galicia-rGz2Z6tVaeg-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Product 4",
    price: 29.99,
    image: "../images/sabrianna-uiKSc7-NM2s-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "Product 5",
    price: 39.99,
    image: "../images/alexis-antoine-r7JZGKGhrf0-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "Product 6",
    price: 49.99,
    image: "../images/atul-mohan-TmOPo7TpLzw-unsplash - Copy.jpg",
    quantity: 1,
  },
  {
    id: 7,
    name: "Product 7",
    price: 29.99,
    image: "../images/carmen-alarcon-PHcEof5kfqk-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 8,
    name: "Product 8",
    price: 39.99,
    image: "../images/sabrianna-ZWwC_6VfdAU-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 9,
    name: "Product 9",
    price: 49.99,
    image: "../images/sabrianna-a9HPsYvWr-E-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 10,
    name: "Product 10",
    price: 29.99,
    image: "../images/sabrianna-uiKSc7-NM2s-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 11,
    name: "Product 11",
    price: 39.99,
    image: "../images/sabrianna-wh_rZqPiCuw-unsplash.jpg",
    quantity: 1,
  },
  {
    id: 12,
    name: "Product 12",
    price: 49.99,
    image: "../images/sabrianna-lbqW0O09RAM-unsplash.jpg",
    quantity: 1,
  },
];
